### ISSUE TITLE
Use iconify cause Error

### ISSUE THREAD

**Issue by CoderMonkie** [CoderMonkie/vue-grabbing-box#2]
```text
TypeError: Cannot read properties of undefined (reading 'on')
    at setCurrentInstance (vue.runtime.esm.js:560:1)
    at callHook$1 (vue.runtime.esm.js:4026:1)
    at Object.insert (vue.runtime.esm.js:4423:1)
    at invokeInsertHook (vue.runtime.esm.js:6942:1)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js:7153:1)
    at Vue._update (vue.runtime.esm.js:3769:1)
    at VueComponent.updateComponent (vue.runtime.esm.js:3868:1)
    at Watcher.get (vue.runtime.esm.js:3446:1)
    at Watcher.run (vue.runtime.esm.js:3522:1)
    at flushSchedulerQueue (vue.runtime.esm.js:4121:1)
```

just followed the doc:
https://github.com/iconify/iconify/tree/main/components/vue2

cause error in some case (vue@2.6.14)

**Comment by CoderMonkie** [comment]
fixed in v0.1.2
